### ISSUE TITLE
Cannot generate documentation

### ISSUE THREAD

**Issue by franklinyu** [mangalam-research/salve#34]
I see that this package depends on [TypeDoc](http://typedoc.org/). When I run `typedoc` I got

```text
Error: …/salve/lib/salve/scripts/convert.ts(496)
 Variable 'convStartTime' is used before being assigned.
```

**Comment by lddubeau** [comment]
That's bizarre. At any rate, I did a fresh installed and noticed that the dependencies provided too much leeway with version numbers. I used npm@5 last year but ran into deal breakers so I reverted to npm@4. I upgraded to npm@5 again and will soon put out an update with a `package-lock.json` that allows replicating exactly my package installation.

I've just released salve version 5.0.0, and I'm unable to get the error you report.

I've noticed though that doing `gulp doc` from a freshly installed clone is not working. You need to do `gulp` first to build the source and then `gulp doc`. I've filed #35 to track the problem.

Please try again with salve version 5.0.0 and keeping in mind the problem I just described. I'm provisionally closing this. I'll reopen if needed.
